### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by SUN123RAY** [lucydot/effmass#40]
Hi 

I am getting the following error. And what will be the command prompt if I want to select  specific band index and k-point index?

Welcome to effmass 2.0.0 🎈
? Which DFT code have you used to generate the bandstructure? Vasp
? What's the path to your Vasp output files? ./../band_gaino/
? How many k-points should I ignore at the start of the file? (useful for hybrid calculations) 0
? How far (in eV) from the CBM (VBM) would you like me to search for minima (maxima)? 0.05
? What would you like the energy range (in eV) of each segment to be? 0.5
? Which values would you like me to calculate? done (2 selections)
? Would you like me to save a plot of the band segments? Yes
? Would you like me to save a summary file? Yes
Reading in data...
Traceback (most recent call last):
  File "/anaconda3/bin/effmass", line 33, in <module>
    sys.exit(load_entry_point('effmass==2.1.0', 'console_scripts', 'effmass')())
  File "/anaconda3/lib/python3.7/site-packages/effmass-2.1.0-py3.7.egg/effmass/cli.py", line 86, in cli
  File "/anaconda3/lib/python3.7/site-packages/effmass-2.1.0-py3.7.egg/effmass/inputs.py", line 346, in __init__
  File "/anaconda3/lib/python3.7/site-packages/vasppy-0.7.1.0-py3.7.egg/vasppy/procar.py", line 300, in from_file
    pcar._read_from_file( filename=filename )
  File "/anaconda3/lib/python3.7/site-packages/vasppy-0.7.1.0-py3.7.egg/vasppy/procar.py", line 326, in _read_from_file
    self.parse_projections()
  File "/anaconda3/lib/python3.7/site-packages/vasppy-0.7.1.0-py3.7.egg/vasppy/procar.py", line 227, in parse_projections
    assert( self._number_of_bands * self._number_of_k_points == len( self.projection_data ) )
AssertionError

**Comment by lucydot** [comment]
Dear @SUN123RAY. Can you confirm that there is a `PROCAR` file in the directory provided (`../band/gaino`)? If so, perhaps you can send me the vasp output files you are using and I will try on my machine.

**Comment by lucydot** [comment]
ps, you should be able to upload the files via Github

**Comment by lucydot** [comment]
Hi @SUN123RAY did you solve the issue you were having - can I close this issue? 

To select a specific band index and k-point you need to use the Python API - it is not an option in the CLI.
